[package]
name = "jetrun-cache"
version.workspace = true
edition.workspace = true

[[bin]]
name = "jetrun-cache"
path = "src/main.rs"

[dependencies]
mimalloc = { workspace = true }
jetrun-common = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
tonic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
blake3 = { workspace = true }
sha2 = { workspace = true }
dashmap = { workspace = true }
bytes = { workspace = true }
memmap2 = { workspace = true }
zstd = { workspace = true }
lz4_flex = { workspace = true }

[dev-dependencies]
tempfile = "3"
